apiVersion: v1
kind: Namespace
metadata:
  name: dns-stress-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dns-stress-test
  name: dns-stress-test
  namespace: dns-stress-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dns-stress-test
  template:
    metadata:
      labels:
        app: dns-stress-test
    spec:
      containers:
      - image: k8s.gcr.io/dns-stress-test:latest
        args:
        - /dns
        - -f
        - /config/sites
        name: dns-stress-test
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        - name: config
          mountPath: /config
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_VARIANT
          value: gke
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_CONTAINER_NAME
          value: dns-stress-test
      volumes:
      - name: google-cloud-key
        secret:
          secretName: dns-stress-test
      - name: config
        configMap:
          name: dns
